channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - numpy
  - pandas
  - pyjwt=2.4.0
  - spacy-model-en_core_web_lg
  - pip:
      - oci==2.70.1
      - oracle-ads==2.6.3
      - pandas==1.3.5
      - beautifulsoup4==4.11.1
      - python-dateutil==2.8.2
      - html5lib==1.1
      - cloudpickle==2.1.0
      - scikit-learn==1.0.2
      - numpy==1.22.2
      - joblib==1.1.0
      - beautifulsoup4==4.11.1
      - requests==2.28.1
      - scipy==1.9.0
      - schedule==1.1.0
      - lxml==4.7.1
      - talon==1.4.4
      - jwt==1.3.1
      - typing-extensions==4.5.0
      - urllib3==1.26.14
      - spacy==3.4.1
      
